import { readFile } from "node:fs/promises";

const html = await readFile("index.html", "utf8");
const audioLabHtml = await readFile("audio-lab.html", "utf8");
const js = await readFile("src/app.js", "utf8");
const css = await readFile("src/styles.css", "utf8");
const api = await readFile("src/api.js", "utf8");
const workflows = await readFile("src/workflows.js", "utf8");
const state = await readFile("src/state.js", "utf8");
const render = await readFile("src/render.js", "utf8");
const audio = await readFile("src/audio.js", "utf8");
const audioLabJs = await readFile("src/audio-lab.js", "utf8");
const audioLabCss = await readFile("src/audio-lab.css", "utf8");
const audioSession = await readFile("src/audio-session.js", "utf8");
const capture = await readFile("src/capture.js", "utf8");
const setMap = await readFile("src/set-map.js", "utf8");
const performanceEvents = await readFile("src/performance-events.js", "utf8");
const pitchAnalysis = await readFile("src/pitch-analysis.js", "utf8");
const smokeApi = await readFile("scripts/smoke-api.mjs", "utf8");
const audioToolbeltTest = await readFile("scripts/audio-toolbelt.test.mjs", "utf8");
const journalHtml = await readFile("journal.html", "utf8");
const journalJs = await readFile("src/journal.js", "utf8");
const journalCss = await readFile("src/journal.css", "utf8");
const pitchGatesHtml = await readFile("pitch-gates.html", "utf8");
const pitchGatesJs = await readFile("src/pitch-gates.js", "utf8");
const pitchGatesCss = await readFile("src/pitch-gates.css", "utf8");
const pitchVendor = await readFile("src/vendor/pitchy.js", "utf8");
const themeJs = await readFile("src/theme.js", "utf8");
const themeCss = await readFile("src/theme.css", "utf8");
const server = await readFile("server.mjs", "utf8");
const env = await readFile("server/env.mjs", "utf8");
const routes = await readFile("server/routes.mjs", "utf8");
const auddProvider = await readFile("server/audd-provider.mjs", "utf8");
const providerSchema = await readFile("server/provider-schema.mjs", "utf8");
const normalizer = await readFile("server/provider-normalizer.mjs", "utf8");
const provider = await readFile("server/recognition-provider.mjs", "utf8");
const archiveStore = await readFile("server/archive-store.mjs", "utf8");
const audioLabDoc = await readFile("docs/AUDIO_LAB.md", "utf8");

assert(html.includes("./src/styles.css"), "index.html should load src/styles.css");
assert(html.includes("./src/app.js"), "index.html should load src/app.js");
assert(html.includes("id=\"setMapCanvas\""), "index.html should include the set map canvas");
assert(html.includes("id=\"apiStatus\""), "index.html should include the API status indicator");
assert(html.includes("id=\"providerName\""), "index.html should include provider status");
assert(html.includes("id=\"providerSetup\""), "index.html should include provider setup status");
assert(html.includes("id=\"providerTestBtn\""), "index.html should include provider test action");
assert(html.includes("class=\"provider-chain\""), "index.html should include provider chain HUD");
assert(html.includes("id=\"nowConfidenceMeter\""), "index.html should include confidence meter");
assert(html.includes("id=\"archiveBtn\""), "index.html should include archive action");
assert(html.includes("id=\"archiveList\""), "index.html should include archive list");
assert(html.includes("id=\"audioEventLog\""), "index.html should include audio event log");
assert(html.includes("data-quick-tag=\"heater\""), "index.html should include quick crate tags");
assert(html.includes("id=\"mergeDuplicateBtn\""), "index.html should include duplicate merge action");
assert(html.includes("./pitch-gates.html"), "index.html should link to Pitch Gates");
assert(html.includes("./audio-lab.html"), "index.html should link to Audio Lab");
assert(html.includes("data-theme-toggle"), "index.html should include the illustrated theme toggle");
assert(html.includes("src/theme.js"), "index.html should load shared theme behavior");
assert(css.includes(".set-map"), "styles.css should include set map styles");
assert(css.includes(".archive-list"), "styles.css should include archive list styles");
assert(css.includes(".provider-panel"), "styles.css should include provider panel styles");
assert(css.includes(".provider-chain"), "styles.css should include provider chain styles");
assert(css.includes(".confidence-meter"), "styles.css should include confidence meter styles");
assert(css.includes("stickerLand"), "styles.css should include capture sticker animation");
assert(css.includes(".audio-event-log"), "styles.css should include audio event log styles");
assert(css.includes(".quick-tag-grid"), "styles.css should include quick tag styles");
assert(css.includes(".duplicate-panel"), "styles.css should include duplicate review styles");
assert(workflows.includes("requestRecognition"), "workflows.js should include the recognition client");
assert(workflows.includes("archiveSet"), "workflows.js should include archive save flow");
assert(workflows.includes("loadArchivedSet"), "workflows.js should include archive load flow");
assert(api.includes("/api/recognize"), "api.js should call the recognition endpoint");
assert(api.includes("/api/providers/diagnostics"), "api.js should call provider diagnostics");
assert(api.includes("audio"), "api.js should include audio window payloads");
assert(api.includes("/api/sets"), "api.js should call the set archive endpoint");
assert(api.includes("/api/sets/"), "api.js should call the set load endpoint");
assert(api.includes("/api/journal"), "api.js should call the journal endpoint");
assert(smokeApi.includes("/api/health"), "smoke-api.mjs should check API health");
assert(smokeApi.includes("/api/recognize"), "smoke-api.mjs should check recognition");
assert(journalHtml.includes("src/journal.js"), "journal.html should load journal.js");
assert(journalHtml.includes("data-paper=\"notebook\""), "journal.html should default to notebook paper");
assert(journalJs.includes("parseJournal"), "journal.js should parse markdown entries");
assert(journalJs.includes("saveJournal"), "journal.js should save markdown source");
assert(journalCss.includes("body[data-paper=\"graph\"]"), "journal.css should include graph paper skin");
assert(journalHtml.includes("data-theme-toggle"), "journal.html should include the illustrated theme toggle");
assert(journalHtml.includes("src/theme.js"), "journal.html should load shared theme behavior");
assert(audioLabHtml.includes("src/audio-lab.js"), "audio-lab.html should load audio-lab.js");
assert(audioLabHtml.includes("id=\"scopeCanvas\""), "audio-lab.html should include oscilloscope canvas");
assert(audioLabHtml.includes("id=\"logSnapshotBtn\""), "audio-lab.html should include snapshot logging");
assert(audioLabHtml.includes("data-demo-midi=\"57\""), "audio-lab.html should include demo pitch controls");
assert(audioLabHtml.includes("data-theme-toggle"), "Audio Lab should include the illustrated theme toggle");
assert(audioLabHtml.includes("src/theme.js"), "Audio Lab should load shared theme behavior");
assert(pitchGatesHtml.includes("id=\"pitchGameCanvas\""), "pitch-gates.html should include its game canvas");
assert(pitchGatesHtml.includes("id=\"toneBtn\""), "pitch-gates.html should include demo tone input");
assert(pitchGatesHtml.includes("id=\"micBtn\""), "pitch-gates.html should include mic input");
assert(pitchGatesHtml.includes("id=\"shareBtn\""), "pitch-gates.html should include shared audio input");
assert(pitchGatesHtml.includes("id=\"fileBtn\""), "pitch-gates.html should include audio-file input");
assert(pitchGatesHtml.includes("id=\"startRoundBtn\""), "pitch-gates.html should include a round control");
assert(pitchGatesHtml.includes("./audio-lab.html"), "Pitch Gates should link to Audio Lab");
assert(pitchGatesHtml.includes("src/pitch-gates.js"), "pitch-gates.html should load its game module");
assert(pitchAnalysis.includes("PitchDetector"), "pitch-analysis.js should use pitch detection");
assert(pitchGatesJs.includes("useAudioFile"), "pitch-gates.js should allow audio files");
assert(pitchGatesJs.includes("useDemoTone"), "pitch-gates.js should expose an immediate demo");
assert(pitchGatesJs.includes("createAudioInputSession"), "Pitch Gates should use the shared audio session");
assert(pitchGatesJs.includes("createPitchAnalyzer"), "Pitch Gates should use the shared pitch analyzer");
assert(pitchGatesJs.includes("persistPerformanceEvent"), "Pitch Gates should use shared performance-event writes");
assert(pitchGatesCss.includes(".screen-shell"), "pitch-gates.css should style its game screen");
assert(pitchGatesCss.includes("@media (max-width: 560px)"), "Pitch Gates should include mobile styling");
assert(pitchVendor.includes("PitchDetector"), "bundled pitch detector should be present");
assert(pitchGatesHtml.includes("data-theme-toggle"), "Pitch Gates should include the illustrated theme toggle");
assert(pitchGatesHtml.includes("src/theme.js"), "Pitch Gates should load shared theme behavior");
assert(themeJs.includes("setscope-theme"), "theme.js should persist the chosen mode");
assert(themeJs.includes("data-theme-toggle"), "theme.js should wire shared theme controls");
assert(themeCss.includes("lightning-bulb-toggle-ui.png") || html.includes("lightning-bulb-toggle-ui.png"), "theme bulb asset should be referenced");
assert(themeCss.includes("data-theme=\"light\""), "theme.css should include light-mode styling");
assert(state.includes("./fixtures.js"), "state.js should import shared fixtures");
assert(state.includes("tagSelectedTrack"), "state.js should support crate tags");
assert(state.includes("logAudioEvent"), "state.js should support audio event logging");
assert(state.includes("persistAudioEvent"), "state.js should persist external audio events without overwriting a newer draft");
assert(state.includes("metadata"), "state.js should preserve structured event metadata");
assert(state.includes("mergeSelectedDuplicate"), "state.js should support duplicate merging");
assert(js.includes("./workflows.js"), "app.js should wire workflows");
assert(js.includes("./render.js"), "app.js should wire rendering");
assert(js.includes("renderProviderStatus"), "app.js should render provider health details");
assert(js.includes("refreshProviderDiagnostics"), "app.js should refresh provider diagnostics");
assert(render.includes("createRenderer"), "render.js should export renderer factory");
assert(render.includes("renderConfidenceMeter"), "render.js should update confidence meter");
assert(render.includes("renderAudioEvents"), "render.js should render audio events");
assert(render.includes("renderTrackTags"), "render.js should render crate tags");
assert(render.includes("renderDuplicateReview"), "render.js should render duplicate review");
assert(audio.includes("estimateBpm"), "audio.js should include BPM analysis");
assert(audioLabJs.includes("createAudioInputSession"), "audio-lab.js should use the shared audio session");
assert(audioLabJs.includes("createPitchAnalyzer"), "audio-lab.js should use the shared pitch analyzer");
assert(audioLabJs.includes("persistPerformanceEvent"), "audio-lab.js should persist structured events");
assert(audioLabJs.includes("drawScope"), "audio-lab.js should draw the oscilloscope trace");
assert(audioLabCss.includes(".scope-screen"), "audio-lab.css should style the oscilloscope screen");
assert(audioSession.includes("createAudioInputSession"), "audio-session.js should expose reusable audio input sessions");
assert(audioSession.includes("getUserMedia"), "audio-session.js should allow microphone input");
assert(audioSession.includes("getDisplayMedia"), "audio-session.js should allow explicitly shared audio");
assert(audioSession.includes("useSharedAudio"), "audio-session.js should support shared audio source setup");
assert(pitchAnalysis.includes("createPitchAnalyzer"), "pitch-analysis.js should expose reusable pitch analysis");
assert(pitchAnalysis.includes("midiToNote"), "pitch-analysis.js should expose musical pitch helpers");
assert(performanceEvents.includes("createPerformanceEvent"), "performance-events.js should create structured performance events");
assert(performanceEvents.includes("metadata"), "performance-events.js should map performance data into audio-event metadata");
assert(performanceEvents.includes("audioEventTypeForMode"), "performance-events.js should map modes to audio event types");
assert(audioToolbeltTest.includes("Audio toolbelt checks passed"), "audio-toolbelt.test.mjs should cover toolbelt contracts");
assert(audioLabDoc.includes("Audio Lab"), "docs/AUDIO_LAB.md should document Audio Lab");
assert(capture.includes("MediaRecorder"), "capture.js should use MediaRecorder for mic windows");
assert(capture.includes("dataUrl"), "capture.js should encode audio windows for API transport");
assert(capture.includes("createSampleAudioPayload"), "capture.js should generate sample provider audio");
assert(setMap.includes("drawSetMap"), "set-map.js should include canvas rendering");
assert(workflows.includes("testProviderWithSample"), "workflows.js should include sample provider testing");
assert(server.includes("./server/routes.mjs"), "server.mjs should wire API routes");
assert(server.includes("./server/static.mjs"), "server.mjs should wire static serving");
assert(server.includes("./server/env.mjs"), "server.mjs should load local env config");
assert(env.includes("loadLocalEnv"), "env.mjs should expose local env loading");
assert(routes.includes("createApiRouter"), "routes.mjs should export API router factory");
assert(routes.includes("/api/providers/diagnostics"), "routes.mjs should expose provider diagnostics");
assert(normalizer.includes("normalizeProviderMatch"), "provider-normalizer.mjs should normalize provider matches");
assert(providerSchema.includes("validateNormalizedMatch"), "provider-schema.mjs should validate matches");
assert(normalizer.includes("./provider-schema.mjs"), "provider normalizer should assert schema");
assert(provider.includes("recognizeAudioWindow"), "recognition-provider.mjs should expose provider adapter contract");
assert(provider.includes("getRecognitionProviderStatus"), "recognition-provider.mjs should expose provider status");
assert(provider.includes("getRecognitionDiagnostics"), "recognition-provider.mjs should expose provider diagnostics");
assert(provider.includes("match-schema"), "recognition diagnostics should expose schema readiness");
assert(normalizer.includes("clampNumber"), "provider-normalizer.mjs should clamp provider numeric fields");
assert(normalizer.includes("normalizeConfidence"), "provider-normalizer.mjs should normalize provider confidence values");
assert(provider.includes("sanitizeAudioMetadata"), "recognition-provider.mjs should sanitize audio metadata");
assert(provider.includes("../src/fixtures.js"), "recognition provider should import shared fixtures");
assert(provider.includes("./audd-provider.mjs"), "recognition provider should use the AudD adapter");
assert(auddProvider.includes("./provider-normalizer.mjs"), "AudD provider should use the shared normalizer");
assert(auddProvider.includes("recognizeWithAudD"), "AudD provider should expose a recognition function");
assert(auddProvider.includes("mapAudDResult"), "AudD provider should expose result mapping for tests");
assert(auddProvider.includes("AUDD_API_TOKEN"), "AudD provider should read server-side API token config");
assert(archiveStore.includes("createArchiveStore"), "archive-store.mjs should export archive store factory");

console.log("SetScope checks passed");

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}
