import { readFile } from "node:fs/promises";

const html = await readFile("index.html", "utf8");
const audioLabHtml = await readFile("audio-lab.html", "utf8");
const js = await readFile("src/app.js", "utf8");
const css = await readFile("src/styles.css", "utf8");
const api = await readFile("src/api.js", "utf8");
const workflows = await readFile("src/workflows.js", "utf8");
const state = await readFile("src/state.js", "utf8");
const render = await readFile("src/render.js", "utf8");
const audio = await readFile("src/audio.js", "utf8");
const audioLabJs = await readFile("src/audio-lab.js", "utf8");
const audioLabCss = await readFile("src/audio-lab.css", "utf8");
const audioSession = await readFile("src/audio-session.js", "utf8");
const audioWidgets = await readFile("src/audio-widgets.js", "utf8");
const capture = await readFile("src/capture.js", "utf8");
const setMap = await readFile("src/set-map.js", "utf8");
const setCoach = await readFile("src/set-coach.js", "utf8");
const djMentor = await readFile("src/dj-mentor.js", "utf8");
const performanceEvents = await readFile("src/performance-events.js", "utf8");
const performanceContract = await readFile("src/contracts/performance-event.js", "utf8");
const performanceMigration = await readFile("src/migrations/performance-event-v1.js", "utf8");
const pitchAnalysis = await readFile("src/pitch-analysis.js", "utf8");
const practiceContext = await readFile("src/practice-context.js", "utf8");
const listeningSession = await readFile("src/listening-session.js", "utf8");
const toolRegistry = await readFile("src/tool-registry.js", "utf8");
const smokeApi = await readFile("scripts/smoke-api.mjs", "utf8");
const runtimeSmoke = await readFile("scripts/runtime-smoke.mjs", "utf8");
const audioToolbeltTest = await readFile("scripts/audio-toolbelt.test.mjs", "utf8");
const journalHtml = await readFile("journal.html", "utf8");
const journalJs = await readFile("src/journal.js", "utf8");
const journalCss = await readFile("src/journal.css", "utf8");
const pitchGatesHtml = await readFile("pitch-gates.html", "utf8");
const pitchGatesJs = await readFile("src/pitch-gates.js", "utf8");
const pitchGatesChallenge = await readFile("src/pitch-gates/challenge.js", "utf8");
const pitchGatesReducer = await readFile("src/pitch-gates/reducer.js", "utf8");
const pitchGatesReplay = await readFile("src/pitch-gates/replay.js", "utf8");
const pitchGatesCss = await readFile("src/pitch-gates.css", "utf8");
const rhythmRouletteHtml = await readFile("rhythm-roulette.html", "utf8");
const rhythmRouletteJs = await readFile("src/rhythm-roulette.js", "utf8");
const rhythmRouletteCss = await readFile("src/rhythm-roulette.css", "utf8");
const pitchVendor = await readFile("src/vendor/pitchy.js", "utf8");
const themeJs = await readFile("src/theme.js", "utf8");
const themeCss = await readFile("src/theme.css", "utf8");
const server = await readFile("server.mjs", "utf8");
const env = await readFile("server/env.mjs", "utf8");
const routes = await readFile("server/routes.mjs", "utf8");
const auddProvider = await readFile("server/audd-provider.mjs", "utf8");
const providerSchema = await readFile("server/provider-schema.mjs", "utf8");
const normalizer = await readFile("server/provider-normalizer.mjs", "utf8");
const provider = await readFile("server/recognition-provider.mjs", "utf8");
const archiveStore = await readFile("server/archive-store.mjs", "utf8");
const audioLabDoc = await readFile("docs/AUDIO_LAB.md", "utf8");

assert(html.includes("./src/styles.css"), "index.html should load src/styles.css");
assert(html.includes("./src/app.js"), "index.html should load src/app.js");
assert(html.includes("id=\"setMapCanvas\""), "index.html should include the set map canvas");
assert(html.includes("id=\"apiStatus\""), "index.html should include the API status indicator");
assert(html.includes("id=\"providerName\""), "index.html should include provider status");
assert(html.includes("id=\"providerSetup\""), "index.html should include provider setup status");
assert(html.includes("id=\"providerTestBtn\""), "index.html should include provider test action");
assert(html.includes("id=\"liveTransport\""), "index.html should include the continuous listening transport");
assert(html.includes("id=\"cadenceSelect\""), "index.html should include recognition cadence control");
assert(html.includes("class=\"provider-chain\""), "index.html should include provider chain HUD");
assert(html.includes("id=\"nowConfidenceMeter\""), "index.html should include confidence meter");
assert(html.includes("id=\"setCoachPanel\""), "index.html should include the Set Coach panel");
assert(html.includes("id=\"coachActionList\""), "index.html should include Set Coach action list");
assert(html.includes("id=\"coachPromptList\""), "index.html should include Set Coach prompt list");
assert(html.includes("id=\"djMentorPanel\""), "index.html should include the DJ Mentor panel");
assert(html.includes("id=\"mentorToolRack\""), "index.html should include contextual Mentor tool launches");
assert(html.includes("id=\"eventMentorCard\""), "index.html should include the event DJ move card");
assert(html.includes("id=\"archiveBtn\""), "index.html should include archive action");
assert(html.includes("id=\"archiveList\""), "index.html should include archive list");
assert(html.includes("id=\"audioEventLog\""), "index.html should include audio event log");
assert(html.includes("id=\"eventDrawer\""), "index.html should include the toolbelt event detail drawer");
assert(html.includes("class=\"deck-legend\""), "the vinyl deck should include a readable hardware status legend");
assert(html.includes("class=\"deck-led-bank\""), "the vinyl deck should include pixel-scale signal instrumentation");
assert(html.includes("id=\"eventTrackSelect\""), "index.html should include event reassignment select");
assert(html.includes("aria-label=\"Import audio file\""), "index.html should label the hidden audio import input");
assert(html.includes("data-signal-filter=\"analysis\""), "index.html should include signal filter controls");
assert(html.includes("data-event-label=\"practice\""), "index.html should include event label controls");
assert(html.includes("id=\"promoteEventBtn\""), "index.html should include promote-to-notes action");
assert(html.includes("data-quick-tag=\"heater\""), "index.html should include quick crate tags");
assert(html.includes("id=\"mergeDuplicateBtn\""), "index.html should include duplicate merge action");
assert(html.includes("./pitch-gates.html"), "index.html should link to Pitch Gates");
assert(html.includes("./audio-lab.html"), "index.html should link to Audio Lab");
assert(html.includes("data-tool-rack"), "index.html should include the shared tool rack");
assert(html.includes("src/tool-registry.js"), "index.html should load the tool registry");
assert(html.includes("data-theme-toggle"), "index.html should include the illustrated theme toggle");
assert(html.includes("src/theme.js"), "index.html should load shared theme behavior");
assert(css.includes(".set-map"), "styles.css should include set map styles");
assert(css.includes(".archive-list"), "styles.css should include archive list styles");
assert(css.includes(".provider-panel"), "styles.css should include provider panel styles");
assert(css.includes(".provider-chain"), "styles.css should include provider chain styles");
assert(css.includes(".live-transport"), "styles.css should include continuous listening transport styles");
assert(css.includes(".confidence-meter"), "styles.css should include confidence meter styles");
assert(css.includes(".set-coach"), "styles.css should include Set Coach styles");
assert(css.includes(".coach-action"), "styles.css should include Set Coach action styles");
assert(css.includes(".dj-mentor"), "styles.css should include DJ Mentor styles");
assert(css.includes(".mentor-tool-rack"), "styles.css should include the Mentor practice deck");
assert(css.includes(".mentor-move-card"), "styles.css should include event mentor move-card styles");
assert(css.includes("stickerLand"), "styles.css should include capture sticker animation");
assert(css.includes(".audio-event-log"), "styles.css should include audio event log styles");
assert(css.includes(".event-meta-strip"), "styles.css should include rich toolbelt event metadata styles");
assert(css.includes(".event-drawer"), "styles.css should include toolbelt event drawer styles");
assert(css.includes("visibility: hidden"), "styles.css should hide the event drawer without document overflow");
assert(css.includes("flex-wrap: wrap"), "styles.css should allow the cockpit header actions to wrap instead of overflowing");
assert(css.includes("clip-path: inset(50%)"), "styles.css should hide file inputs without off-document positioning");
assert(css.includes(".signal-filter-rack"), "styles.css should include signal filter styles");
assert(css.includes(".event-label-rack"), "styles.css should include event label styles");
assert(css.includes(".track-event-strip"), "styles.css should include timeline toolbelt signal styles");
assert(css.includes(".moment-toolbelt"), "styles.css should include selected-track toolbelt signal styles");
assert(css.includes("container-type: inline-size"), "the vinyl deck should size internal labels against its own width");
assert(css.includes(".quick-tag-grid"), "styles.css should include quick tag styles");
assert(css.includes(".duplicate-panel"), "styles.css should include duplicate review styles");
assert(workflows.includes("requestRecognition"), "workflows.js should include the recognition client");
assert(workflows.includes("createListeningSession"), "workflows.js should use the continuous listening controller");
assert(listeningSession.includes("maxConsecutiveErrors"), "listening-session.js should guard repeated recognition failures");
assert(listeningSession.includes("abortController"), "listening-session.js should cancel active capture and recognition work");
assert(workflows.includes("archiveSet"), "workflows.js should include archive save flow");
assert(workflows.includes("loadArchivedSet"), "workflows.js should include archive load flow");
assert(api.includes("/api/recognize"), "api.js should call the recognition endpoint");
assert(api.includes("/api/providers/diagnostics"), "api.js should call provider diagnostics");
assert(api.includes("audio"), "api.js should include audio window payloads");
assert(api.includes("/api/sets"), "api.js should call the set archive endpoint");
assert(api.includes("/api/sets/"), "api.js should call the set load endpoint");
assert(api.includes("/api/journal"), "api.js should call the journal endpoint");
assert(smokeApi.includes("/api/health"), "smoke-api.mjs should check API health");
assert(smokeApi.includes("/api/recognize"), "smoke-api.mjs should check recognition");
assert(runtimeSmoke.includes("chromium.launch"), "runtime-smoke.mjs should launch Playwright Chromium");
assert(runtimeSmoke.includes("verifySetScope"), "runtime-smoke.mjs should test the main cockpit");
assert(runtimeSmoke.includes("verifyContextualPracticeLoop"), "runtime-smoke.mjs should test the practice return loop");
assert(runtimeSmoke.includes("verifyLiveListening"), "runtime-smoke.mjs should test continuous listening start and stop");
assert(runtimeSmoke.includes("verifyRhythmRoulette"), "runtime-smoke.mjs should test Rhythm Roulette");
assert(runtimeSmoke.includes("verifyPitchGates"), "runtime-smoke.mjs should test Pitch Gates");
assert(runtimeSmoke.includes("verifyAudioLab"), "runtime-smoke.mjs should test Audio Lab");
assert(runtimeSmoke.includes("verifyJournal"), "runtime-smoke.mjs should test the Dev Journal");
assert(runtimeSmoke.includes("page.screenshot"), "runtime-smoke.mjs should capture screenshots");
assert(runtimeSmoke.includes("overflowX"), "runtime-smoke.mjs should check horizontal overflow");
assert(journalHtml.includes("src/journal.js"), "journal.html should load journal.js");
assert(journalHtml.includes("data-paper=\"notebook\""), "journal.html should default to notebook paper");
assert(journalHtml.includes("<h1>Dev Journal</h1>"), "journal.html should expose a semantic page heading");
assert(journalHtml.includes("aria-label=\"Entry title\""), "journal.html should label the editable title");
assert(journalHtml.includes("aria-label=\"Entry body\""), "journal.html should label the editable body");
assert(journalHtml.includes("aria-label=\"Markdown source\""), "journal.html should label the source editor");
assert(journalJs.includes("parseJournal"), "journal.js should parse markdown entries");
assert(journalJs.includes("saveJournal"), "journal.js should save markdown source");
assert(journalCss.includes("body[data-paper=\"graph\"]"), "journal.css should include graph paper skin");
assert(journalHtml.includes("data-theme-toggle"), "journal.html should include the illustrated theme toggle");
assert(journalHtml.includes("src/theme.js"), "journal.html should load shared theme behavior");
assert(audioLabHtml.includes("src/audio-lab.js"), "audio-lab.html should load audio-lab.js");
assert(audioLabHtml.includes("<h1>Audio Lab</h1>"), "audio-lab.html should expose a semantic page heading");
assert(audioLabHtml.includes("id=\"scopeCanvas\""), "audio-lab.html should include oscilloscope canvas");
assert(audioLabHtml.includes("aria-label=\"Choose audio file\""), "audio-lab.html should label the hidden audio file input");
assert(audioLabHtml.includes("id=\"logSnapshotBtn\""), "audio-lab.html should include snapshot logging");
assert(audioLabHtml.includes("data-demo-midi=\"57\""), "audio-lab.html should include demo pitch controls");
assert(audioLabHtml.includes("data-target-midi=\"57\""), "audio-lab.html should include tuner target controls");
assert(audioLabHtml.includes("id=\"gainControl\""), "audio-lab.html should include scope gain control");
assert(audioLabHtml.includes("id=\"timeScaleControl\""), "audio-lab.html should include scope time control");
assert(audioLabHtml.includes("id=\"freezeScopeBtn\""), "audio-lab.html should include scope freeze control");
assert(audioLabHtml.includes("id=\"holdMeter\""), "audio-lab.html should include tuner hold meter");
assert(audioLabHtml.includes("data-preset=\"guitar\""), "audio-lab.html should include instrument presets");
assert(audioLabHtml.includes("id=\"inputGainControl\""), "audio-lab.html should include input gain calibration");
assert(audioLabHtml.includes("id=\"triggerScopeBtn\""), "audio-lab.html should include scope trigger control");
assert(audioLabHtml.includes("id=\"rmsValue\""), "audio-lab.html should include RMS metering");
assert(audioLabHtml.includes("id=\"peakValue\""), "audio-lab.html should include peak metering");
assert(audioLabHtml.includes("id=\"practiceStatus\""), "audio-lab.html should include practice stats");
assert(audioLabHtml.includes("id=\"trackAttachSelect\""), "audio-lab.html should attach snapshots to set tracks");
assert(audioLabHtml.includes("data-practice-context"), "Audio Lab should show contextual set assignments");
assert(audioLabHtml.includes("data-tool-rack"), "Audio Lab should include the shared tool rack");
assert(audioLabHtml.includes("src/tool-registry.js"), "Audio Lab should load the tool registry");
assert(audioLabHtml.includes("data-theme-toggle"), "Audio Lab should include the illustrated theme toggle");
assert(audioLabHtml.includes("src/theme.js"), "Audio Lab should load shared theme behavior");
assert(pitchGatesHtml.includes("id=\"pitchGameCanvas\""), "pitch-gates.html should include its game canvas");
assert(pitchGatesHtml.includes("<h1>Pitch Gates</h1>"), "pitch-gates.html should expose a semantic page heading");
assert(pitchGatesHtml.includes("id=\"toneBtn\""), "pitch-gates.html should include demo tone input");
assert(pitchGatesHtml.includes("id=\"micBtn\""), "pitch-gates.html should include mic input");
assert(pitchGatesHtml.includes("id=\"shareBtn\""), "pitch-gates.html should include shared audio input");
assert(pitchGatesHtml.includes("id=\"fileBtn\""), "pitch-gates.html should include audio-file input");
assert(pitchGatesHtml.includes("aria-label=\"Choose audio file\""), "pitch-gates.html should label the hidden audio file input");
assert(pitchGatesHtml.includes("id=\"startRoundBtn\""), "pitch-gates.html should include a round control");
assert(pitchGatesHtml.includes("data-practice-context"), "Pitch Gates should show contextual set assignments");
assert(pitchGatesHtml.includes("data-tool-rack") && toolRegistry.includes("./audio-lab.html"), "Pitch Gates should link to Audio Lab through the tool rack");
assert(pitchGatesHtml.includes("data-tool-rack"), "Pitch Gates should include the shared tool rack");
assert(pitchGatesHtml.includes("src/tool-registry.js"), "Pitch Gates should load the tool registry");
assert(pitchGatesHtml.includes("src/pitch-gates.js"), "pitch-gates.html should load its game module");
assert(pitchAnalysis.includes("PitchDetector"), "pitch-analysis.js should use pitch detection");
assert(pitchGatesJs.includes("useAudioFile"), "pitch-gates.js should allow audio files");
assert(pitchGatesJs.includes("useDemoTone"), "pitch-gates.js should expose an immediate demo");
assert(pitchGatesJs.includes("createRoundClock"), "Pitch Gates should bind runs to a stable source clock");
assert(pitchGatesChallenge.includes("createSeededRandom"), "Pitch Gates challenges should use a seeded generator");
assert(!pitchGatesChallenge.includes("Math.random"), "Pitch Gates challenge generation should not use Math.random");
assert(pitchGatesReducer.includes("advancePitchGatesTo"), "Pitch Gates should advance through a pure time boundary");
assert(pitchGatesReducer.includes("pausePitchGatesRun") && pitchGatesReducer.includes("resumePitchGatesRun"), "Pitch Gates reducer should own pause and resume state");
assert(!pitchGatesReducer.includes("document") && !pitchGatesReducer.includes("requestAnimationFrame"), "Pitch Gates reducer should remain independent of rendering");
assert(pitchGatesReplay.includes("expectedHash"), "Pitch Gates replays should carry deterministic verification hashes");
assert(pitchGatesJs.includes("createAudioInputSession"), "Pitch Gates should use the shared audio session");
assert(pitchGatesJs.includes("createPitchAnalyzer"), "Pitch Gates should use the shared pitch analyzer");
assert(pitchGatesJs.includes("persistPerformanceEvent"), "Pitch Gates should use shared performance-event writes");
assert(pitchGatesJs.includes("mountPracticeContext"), "Pitch Gates should attach contextual practice runs");
assert(pitchGatesCss.includes(".screen-shell"), "pitch-gates.css should style its game screen");
assert(pitchGatesCss.includes("@media (max-width: 560px)"), "Pitch Gates should include mobile styling");
assert(pitchVendor.includes("PitchDetector"), "bundled pitch detector should be present");
assert(pitchGatesHtml.includes("data-theme-toggle"), "Pitch Gates should include the illustrated theme toggle");
assert(pitchGatesHtml.includes("src/theme.js"), "Pitch Gates should load shared theme behavior");
assert(rhythmRouletteHtml.includes("<h1>Rhythm Roulette</h1>"), "Rhythm Roulette should expose a semantic page heading");
assert(rhythmRouletteHtml.includes("id=\"rouletteSceneCanvas\""), "Rhythm Roulette should include a pixel art canvas");
assert(rhythmRouletteHtml.includes("id=\"blindDigBtn\""), "Rhythm Roulette should include a blind dig action");
assert(rhythmRouletteHtml.includes("id=\"challengeBadge\""), "Rhythm Roulette should include a constraint badge");
assert(rhythmRouletteHtml.includes("id=\"currentSampleReadout\""), "Rhythm Roulette should include a selected sample readout");
assert(rhythmRouletteHtml.includes("id=\"crateReceipt\""), "Rhythm Roulette should include a crate receipt");
assert(rhythmRouletteHtml.includes("data-practice-context"), "Rhythm Roulette should show contextual set assignments");
assert(rhythmRouletteHtml.includes("id=\"sampleBank\""), "Rhythm Roulette should include sample pads");
assert(rhythmRouletteHtml.includes("id=\"sequencerGrid\""), "Rhythm Roulette should include a beat grid");
assert(rhythmRouletteHtml.includes("data-current-tool=\"rhythm-roulette\""), "Rhythm Roulette should use the shared tool rack");
assert(rhythmRouletteHtml.includes("src/rhythm-roulette.js"), "Rhythm Roulette should load its game module");
assert(rhythmRouletteHtml.includes("data-theme-toggle"), "Rhythm Roulette should include the illustrated theme toggle");
assert(rhythmRouletteJs.includes("blindDig"), "rhythm-roulette.js should implement blind crate pulls");
assert(rhythmRouletteJs.includes("challenges"), "rhythm-roulette.js should include producer constraints");
assert(rhythmRouletteJs.includes("renderCrateReceipt"), "rhythm-roulette.js should render the crate receipt");
assert(rhythmRouletteJs.includes("autoFlipBeat"), "rhythm-roulette.js should generate a starter beat");
assert(rhythmRouletteJs.includes("playSample"), "rhythm-roulette.js should play generated beat sounds");
assert(rhythmRouletteJs.includes("createRhythmRouletteCompletionEvent"), "Rhythm Roulette should persist structured performance events");
assert(rhythmRouletteJs.includes("mountPracticeContext"), "Rhythm Roulette should attach contextual practice runs");
assert(rhythmRouletteJs.includes("drawProducer"), "Rhythm Roulette should draw pixel hip-hop scene art");
assert(rhythmRouletteCss.includes(".record-shop-screen"), "rhythm-roulette.css should style the pixel record shop screen");
assert(rhythmRouletteCss.includes(".roulette-marquee"), "rhythm-roulette.css should style the game marquee");
assert(rhythmRouletteCss.includes(".crate-receipt"), "rhythm-roulette.css should style the crate receipt");
assert(rhythmRouletteCss.includes(".sequencer"), "rhythm-roulette.css should style the beat grid");
assert(rhythmRouletteCss.includes("@media (max-width: 640px)"), "Rhythm Roulette should include mobile styling");
assert(themeJs.includes("setscope-theme"), "theme.js should persist the chosen mode");
assert(themeJs.includes("data-theme-toggle"), "theme.js should wire shared theme controls");
assert(themeCss.includes("lightning-bulb-toggle-ui.png") || html.includes("lightning-bulb-toggle-ui.png"), "theme bulb asset should be referenced");
assert(themeCss.includes("data-theme=\"light\""), "theme.css should include light-mode styling");
assert(themeCss.includes(".tool-rack-item"), "theme.css should style the shared tool rack");
assert(themeCss.includes(".practice-context"), "theme.css should style shared practice assignments");
assert(state.includes("./fixtures.js"), "state.js should import shared fixtures");
assert(state.includes("tagSelectedTrack"), "state.js should support crate tags");
assert(state.includes("logAudioEvent"), "state.js should support audio event logging");
assert(state.includes("persistAudioEvent"), "state.js should persist external audio events without overwriting a newer draft");
assert(state.includes("metadata"), "state.js should preserve structured event metadata");
assert(state.includes("audioEventsForTrack"), "state.js should expose attached toolbelt events by track");
assert(state.includes("signalFilter"), "state.js should persist signal filter state");
assert(state.includes("toggleAudioEventLabel"), "state.js should support event labels");
assert(state.includes("trackMatchesSignalFilter"), "state.js should filter tracks by attached signals");
assert(state.includes("getAudioEventById"), "state.js should expose audio event lookup by id");
assert(state.includes("reassignAudioEvent"), "state.js should support event reassignment");
assert(state.includes("promoteAudioEventToTrackNotes"), "state.js should promote event signals to track notes");
assert(state.includes("appendSelectedTrackNote"), "state.js should append mentor notes to selected tracks");
assert(state.includes("mergeSelectedDuplicate"), "state.js should support duplicate merging");
assert(js.includes("./workflows.js"), "app.js should wire workflows");
assert(js.includes("./render.js"), "app.js should wire rendering");
assert(js.includes("openAudioEvent"), "app.js should open audio event details");
assert(js.includes("promoteSelectedAudioEvent"), "app.js should promote selected audio events");
assert(js.includes("setSignalFilter"), "app.js should wire signal filtering");
assert(js.includes("toggleSelectedEventLabel"), "app.js should wire event labels");
assert(js.includes("runCoachAction"), "app.js should wire Set Coach actions");
assert(js.includes("mentor-note"), "app.js should save DJ Mentor notes");
assert(js.includes("renderProviderStatus"), "app.js should render provider health details");
assert(js.includes("refreshProviderDiagnostics"), "app.js should refresh provider diagnostics");
assert(render.includes("createRenderer"), "render.js should export renderer factory");
assert(render.includes("./set-coach.js"), "render.js should render the Set Coach model");
assert(render.includes("./dj-mentor.js"), "render.js should render the DJ Mentor model");
assert(render.includes("renderSetCoach"), "render.js should render the Set Coach panel");
assert(render.includes("renderDjMentor"), "render.js should render the DJ Mentor panel");
assert(render.includes("renderEventMentorCard"), "render.js should render event DJ move cards");
assert(render.includes("data-coach-event-id"), "render.js should keep coach event ids separate from event-card ids");
assert(render.includes("renderConfidenceMeter"), "render.js should update confidence meter");
assert(render.includes("renderAudioEvents"), "render.js should render audio events");
assert(render.includes("renderTrackEventStrip"), "render.js should render timeline toolbelt signal badges");
assert(render.includes("renderTrackToolbeltMoments"), "render.js should render selected-track toolbelt signals");
assert(render.includes("renderEventMetadata"), "render.js should render rich toolbelt event metadata");
assert(render.includes("renderEventDetail"), "render.js should render toolbelt event detail drawer");
assert(!render.includes("eventDrawer.style.left"), "render.js should leave drawer positioning to CSS");
assert(render.includes("renderEventLabelButtons"), "render.js should render event label buttons");
assert(render.includes("renderTrackTags"), "render.js should render crate tags");
assert(render.includes("renderDuplicateReview"), "render.js should render duplicate review");
assert(audio.includes("estimateBpm"), "audio.js should include BPM analysis");
assert(audioLabJs.includes("createAudioInputSession"), "audio-lab.js should use the shared audio session");
assert(audioLabJs.includes("createPitchAnalyzer"), "audio-lab.js should use the shared pitch analyzer");
assert(audioLabJs.includes("persistPerformanceEvent"), "audio-lab.js should persist structured events");
assert(audioLabJs.includes("drawScope"), "audio-lab.js should draw the oscilloscope trace");
assert(audioLabJs.includes("drawCenterLine"), "audio-lab.js should draw an oscilloscope center line");
assert(audioLabJs.includes("scopeGain"), "audio-lab.js should control oscilloscope gain");
assert(audioLabJs.includes("timeScale"), "audio-lab.js should control oscilloscope time scale");
assert(audioLabJs.includes("toggleFreezeScope"), "audio-lab.js should freeze the scope trace");
assert(audioLabJs.includes("toggleTriggerScope"), "audio-lab.js should trigger-lock the scope trace");
assert(audioLabJs.includes("analyzeLevel"), "audio-lab.js should use shared level metering");
assert(audioLabJs.includes("tunerPresets"), "audio-lab.js should use shared instrument presets");
assert(audioLabJs.includes("recordPracticeLock"), "audio-lab.js should record practice streaks");
assert(audioLabJs.includes("trackAttachSelect"), "audio-lab.js should attach snapshots to timeline tracks");
assert(audioLabJs.includes("mountPracticeContext"), "Audio Lab should preselect contextual assignments");
assert(audioLabJs.includes("Need signal"), "audio-lab.js should prevent empty snapshot logs");
assert(audioLabJs.includes("updateHoldState"), "audio-lab.js should track tuner hold stability");
assert(audioLabCss.includes(".scope-screen"), "audio-lab.css should style the oscilloscope screen");
assert(audioLabCss.includes(".hold-meter"), "audio-lab.css should style tuner hold progress");
assert(audioLabCss.includes(".lab-slider"), "audio-lab.css should style scope controls");
assert(audioLabCss.includes(".level-strip"), "audio-lab.css should style input level meters");
assert(audioSession.includes("createAudioInputSession"), "audio-session.js should expose reusable audio input sessions");
assert(audioSession.includes("getUserMedia"), "audio-session.js should allow microphone input");
assert(audioSession.includes("getDisplayMedia"), "audio-session.js should allow explicitly shared audio");
assert(audioSession.includes("useSharedAudio"), "audio-session.js should support shared audio source setup");
assert(pitchAnalysis.includes("createPitchAnalyzer"), "pitch-analysis.js should expose reusable pitch analysis");
assert(pitchAnalysis.includes("midiToNote"), "pitch-analysis.js should expose musical pitch helpers");
assert(audioWidgets.includes("tunerPresets"), "audio-widgets.js should define reusable tuner presets");
assert(audioWidgets.includes("analyzeLevel"), "audio-widgets.js should expose level metering");
assert(audioWidgets.includes("findZeroCrossingIndex"), "audio-widgets.js should expose zero-crossing trigger helpers");
assert(audioWidgets.includes("loadPracticeStats"), "audio-widgets.js should expose practice stat storage");
assert(toolRegistry.includes("renderToolRack"), "tool-registry.js should render shared tool navigation");
assert(toolRegistry.includes("audio-lab"), "tool-registry.js should register Audio Lab");
assert(toolRegistry.includes("pitch-gates"), "tool-registry.js should register Pitch Gates");
assert(toolRegistry.includes("rhythm-roulette"), "tool-registry.js should register Rhythm Roulette");
assert(performanceEvents.includes("createPerformanceEvent"), "performance-events.js should create structured performance events");
assert(performanceEvents.includes("metadata"), "performance-events.js should map performance data into audio-event metadata");
assert(performanceEvents.includes("trackId"), "performance-events.js should preserve set timeline attachment");
assert(performanceEvents.includes("audioEventTypeForMode"), "performance-events.js should map modes to audio event types");
assert(performanceEvents.includes("labelsForMode"), "performance events should receive searchable practice labels");
assert(performanceEvents.includes("createRhythmRouletteCompletionEvent"), "performance-events.js should create Rhythm Roulette events");
assert(performanceEvents.includes("normalizePerformanceMetadata"), "performance event writes should validate and migrate metadata");
assert(performanceContract.includes("PERFORMANCE_EVENT_V2"), "performance events should have a stable V2 schema id");
assert(performanceContract.includes("eligibleForMastery"), "performance contracts should separate mastery eligibility from score");
assert(performanceMigration.includes("quarantineMetadata"), "malformed performance metadata should be quarantined");
assert(audioToolbeltTest.includes("Audio toolbelt checks passed"), "audio-toolbelt.test.mjs should cover toolbelt contracts");
assert(audioLabDoc.includes("Audio Lab"), "docs/AUDIO_LAB.md should document Audio Lab");
assert(capture.includes("MediaRecorder"), "capture.js should use MediaRecorder for mic windows");
assert(capture.includes("dataUrl"), "capture.js should encode audio windows for API transport");
assert(capture.includes("createSampleAudioPayload"), "capture.js should generate sample provider audio");
assert(setMap.includes("drawSetMap"), "set-map.js should include canvas rendering");
assert(setCoach.includes("createSetCoachModel"), "set-coach.js should compute the Set Coach model");
assert(setCoach.includes("readinessScore"), "set-coach.js should compute readiness score");
assert(setCoach.includes("buildCoachActions"), "set-coach.js should rank coach actions");
assert(setCoach.includes("buildCreativePrompts"), "set-coach.js should create creative prompts");
assert(djMentor.includes("createDjMentorModel"), "dj-mentor.js should compute the DJ Mentor model");
assert(djMentor.includes("createDjMoveCard"), "dj-mentor.js should create event move cards");
assert(djMentor.includes("practiceMission"), "dj-mentor.js should create practice missions");
assert(djMentor.includes("digPrompt"), "dj-mentor.js should create dig prompts");
assert(djMentor.includes("practiceToolsForTrack"), "DJ Mentor should create track-scoped practice launches");
assert(practiceContext.includes("resolvePracticeContext"), "practice-context.js should resolve track assignments");
assert(practiceContext.includes("buildSetReturnHref"), "practice-context.js should build exact return links");
assert(workflows.includes("testProviderWithSample"), "workflows.js should include sample provider testing");
assert(server.includes("./server/routes.mjs"), "server.mjs should wire API routes");
assert(server.includes("./server/static.mjs"), "server.mjs should wire static serving");
assert(server.includes("./server/env.mjs"), "server.mjs should load local env config");
assert(env.includes("loadLocalEnv"), "env.mjs should expose local env loading");
assert(routes.includes("createApiRouter"), "routes.mjs should export API router factory");
assert(routes.includes("/api/providers/diagnostics"), "routes.mjs should expose provider diagnostics");
assert(normalizer.includes("normalizeProviderMatch"), "provider-normalizer.mjs should normalize provider matches");
assert(providerSchema.includes("validateNormalizedMatch"), "provider-schema.mjs should validate matches");
assert(normalizer.includes("./provider-schema.mjs"), "provider normalizer should assert schema");
assert(provider.includes("recognizeAudioWindow"), "recognition-provider.mjs should expose provider adapter contract");
assert(provider.includes("getRecognitionProviderStatus"), "recognition-provider.mjs should expose provider status");
assert(provider.includes("getRecognitionDiagnostics"), "recognition-provider.mjs should expose provider diagnostics");
assert(provider.includes("match-schema"), "recognition diagnostics should expose schema readiness");
assert(normalizer.includes("clampNumber"), "provider-normalizer.mjs should clamp provider numeric fields");
assert(normalizer.includes("normalizeConfidence"), "provider-normalizer.mjs should normalize provider confidence values");
assert(provider.includes("sanitizeAudioMetadata"), "recognition-provider.mjs should sanitize audio metadata");
assert(provider.includes("../src/fixtures.js"), "recognition provider should import shared fixtures");
assert(provider.includes("./audd-provider.mjs"), "recognition provider should use the AudD adapter");
assert(auddProvider.includes("./provider-normalizer.mjs"), "AudD provider should use the shared normalizer");
assert(auddProvider.includes("recognizeWithAudD"), "AudD provider should expose a recognition function");
assert(auddProvider.includes("mapAudDResult"), "AudD provider should expose result mapping for tests");
assert(auddProvider.includes("AUDD_API_TOKEN"), "AudD provider should read server-side API token config");
assert(archiveStore.includes("createArchiveStore"), "archive-store.mjs should export archive store factory");

console.log("SetScope checks passed");

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}
