export const demoTracks = [
  {
    time: "00:00",
    title: "Warm Up The Room",
    artist: "K.M. Session Band",
    bpm: 94,
    key: "9A",
    transition: "Blend",
    confidence: 91,
    wave: 38,
    colors: ["#f0ad4e", "#75d7b6", "#ec6f7e"],
    era: "Late 70s soul",
    label: "Private press",
    source: "Drum break friendly",
    texture: "Brushed hats",
    lineage: "Funk 45s -> park-jam breaks -> sample-era hip-hop",
    why: "The intro leaves room for the next record, then the bass lands without crowding the vocal pocket.",
    needsReview: false,
    status: "matched",
    provider: "setscope-stub",
    notes:
      "A brushed-soul opener with enough swing to let a DJ blend into boom-bap, broken beat, or early disco without shocking the floor.",
  },
  {
    time: "04:26",
    title: "Palm Trees At Noon",
    artist: "The Lowpass District",
    bpm: 96,
    key: "9A",
    transition: "Loop tease",
    confidence: 87,
    wave: 57,
    colors: ["#6ec6ff", "#f0ad4e", "#75d7b6"],
    era: "Early 80s boogie",
    label: "12-inch promo",
    source: "Synth bass lineage",
    texture: "Rubber bass",
    lineage: "Post-disco boogie -> roller rink funk -> modern house edits",
    why: "The percussion loop keeps the room locked while the synth bass quietly changes the color temperature.",
    needsReview: false,
    status: "matched",
    provider: "setscope-stub",
    notes:
      "The percussion bed gives the outgoing track a small lift while the bassline stays harmonically close, which makes the transition feel conversational.",
  },
  {
    time: "09:54",
    title: "Rooftop Latin Quarter",
    artist: "Marisol Vega Ensemble",
    bpm: 101,
    key: "10A",
    transition: "Blend",
    confidence: 93,
    wave: 72,
    colors: ["#ec6f7e", "#6ec6ff", "#f0ad4e"],
    era: "70s Latin funk",
    label: "Reissue cut",
    source: "Montuno break",
    texture: "Hand percussion",
    lineage: "Latin soul clubs -> block parties -> golden-era sample crates",
    why: "The tempo bump reads as excitement because the percussion arrives before the bass fully commits.",
    needsReview: false,
    status: "matched",
    provider: "setscope-stub",
    notes:
      "A tempo nudge and percussion-forward intro create a clean bridge from head-nod soul into dancefloor Latin funk.",
  },
  {
    time: "16:31",
    title: "Needle Talk",
    artist: "Basement Syntax",
    bpm: 105,
    key: "2A",
    transition: "Cut",
    confidence: 82,
    wave: 44,
    colors: ["#75d7b6", "#ec6f7e", "#6ec6ff"],
    era: "90s underground",
    label: "White label",
    source: "Scratch phrase",
    texture: "Dusty drums",
    lineage: "Battle records -> mixtape interludes -> turntablist routines",
    why: "The cut works because the outgoing groove already implied the snare placement of the next record.",
    needsReview: true,
    status: "review",
    provider: "setscope-stub",
    notes:
      "The quick cut resets the groove and makes the drums feel intentional, like the set is moving from discovery into command mode.",
  },
];

export function cloneDemoTracks(withId = () => undefined) {
  return demoTracks.map((track) => ({
    ...structuredClone(track),
    id: withId(),
  }));
}
